export const countryShortName = {
	Germany: "GER",
	Scotland: "SCO",
	Hungary: "HUN",
	Switzerland: "SUI",
	Spain: "ESP",
	Croatia: "CRO",
	Italy: "ITA",
	Albania: "ALB",
	Slovenia: "SVN",
	Denmark: "DEN",
	Serbia: "SRB",
	England: "ENG",
	Poland: "POL",
	Netherlands: "NED",
	Austria: "AUT",
	France: "FRA",
	Belgium: "BEL",
	Slovakia: "SVK",
	Romania: "ROU",
	Ukraine: "UKR",
	Turkey: "TUR",
	Georgia: "GEO",
	Portugal: "POR",
	"Czech Republic": "CZE",
};
