export const countryFlags = {
	Germany: "https://flagsapi.com/DE/flat/64.png",
	Scotland: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Flag_of_Scotland.svg/1200px-Flag_of_Scotland.svg.png",
	Hungary: "https://flagsapi.com/HU/flat/64.png",
	Switzerland: "https://flagsapi.com/CH/flat/64.png",
	Spain: "https://flagsapi.com/ES/flat/64.png",
	Croatia: "https://flagsapi.com/HR/flat/64.png",
	Italy: "https://flagsapi.com/IT/flat/64.png",
	Albania: "https://flagsapi.com/AL/flat/64.png",
	Slovenia: "https://flagsapi.com/SI/flat/64.png",
	Denmark: "https://flagsapi.com/DK/flat/64.png",
	Serbia: "https://flagsapi.com/RS/flat/64.png",
	England: "https://flagsapi.com/GB/flat/64.png",
	Poland: "https://flagsapi.com/PL/flat/64.png",
	Netherlands: "https://flagsapi.com/NL/flat/64.png",
	Austria: "https://flagsapi.com/AT/flat/64.png",
	France: "https://flagsapi.com/FR/flat/64.png",
	Belgium: "https://flagsapi.com/BE/flat/64.png",
	Slovakia: "https://flagsapi.com/SK/flat/64.png",
	Romania: "https://flagsapi.com/RO/flat/64.png",
	Ukraine: "https://flagsapi.com/UA/flat/64.png",
	Turkey: "https://flagsapi.com/TR/flat/64.png",
	Georgia: "https://flagsapi.com/GE/flat/64.png",
	Portugal: "https://flagsapi.com/PT/flat/64.png",
	"Czech Republic": "https://flagsapi.com/CZ/flat/64.png",
};
